env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
gomod:
  proxy: false

builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
    #- arm
    #- arm64
  goarm:
    - "7"
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.version={{ .Version }} -X main.commitSha={{.Commit}} -X main.buildDate={{ .Date }} -extldflags "-static"
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  sort: 'asc'
  filters:
    exclude: ['^docs:', '^test:', '^chore:', 'Merge pull request', 'Merge branch', 'go mod tidy']

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
    - config.toml

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}_{{ .Version }}{{ end }}'
    maintainer: 'Aborche <zhecka@gmail.com>'
    vendor: 'Abdul Khaliq <a.khaliq@outlook.my>'
    description: KC PGSQL PAM provides a password grant token from keycloak for Pluggable Authentication Modules (PAM) SSO.
    license: MIT
    formats:
    - deb
    - rpm
    bindir: /opt/{{ .ProjectName }}
    contents:
      - src: config.toml
        dst: /opt/{{ .ProjectName }}/config.toml

